<?php
/**
 * Amadeco PopularSearchTerms Module
 *
 * @category   Amadeco
 * @package    Amadeco_PopularSearchTerms
 * @author     Ilan Parmentier
 */

/**
 * @var Amadeco\PopularSearchTerms\Block\SearchTerms $block
 * @var Magento\Framework\Escaper $escaper
 */
?>
<div class="block block-search-terms <?= $escaper->escapeHtmlAttr($block->getCssClass() ?? '') ?>">
    <div class="block-title">
        <strong role="heading" aria-level="2"><?= $escaper->escapeHtml(__('Search Terms')) ?></strong>
    </div>
    <div class="block-content">
        <div id="amadeco-search-terms" data-bind="scope: 'search-terms'" class="amadeco-search-terms"></div>
    </div>
</div>

<script type="text/x-magento-init">
{
    "#amadeco-search-terms": {
        "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>
    }
}
</script>
